/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
#include "STM32F103x6_GPIO.h"
#include "STM32F103x6_USART.h"


void clock_Init(void)
{
	//Enable Clock FOR GPIOA
	RCC_GPIOA_CLK_EN();
	//Enable Clock FOR GPIOB
	RCC_GPIOB_CLK_EN();

	//Enable AFIO Clock
	RCC_AFIO_CLK_EN();
}

uint16_t ch;

void UART_IRQ_CallBack(void)
{
	MCAL_UART_ReceiveData(USART1, &ch, disable);
	MCAL_UART_SendData(USART1, &ch, enable);
}


int main(void)
{
	UART_Config UART_CFG;
	clock_Init();

	UART_CFG.BaudRate = UART_BAUD_RATE_115200;
	UART_CFG.HwFlowCtl= UART_HwFlowCtl_NONE;
	UART_CFG.Parity_Mode= UART_Parity_Mode_NONE;
	UART_CFG.IQR_Enable = UART_IRQ_Enable_RXNE;
	UART_CFG.Payload_Length =UART_PayLoad_Length_8B;
	UART_CFG.StopBits = UART_StopBits__1;
	UART_CFG.USART_Mode = UART_MODE_TX_RX;
	UART_CFG.P_IRQ_Handler = UART_IRQ_CallBack;

	MCAL_UART_Init(USART1, &UART_CFG);
	MCAL_UART_GPIO_Set_Pins(USART1);

	while(1);
}








