/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile unsigned int vuint32_t ;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
// register address

//RCC
#define RCC_BASE 	0x40021000
#define RCC_APB2ENR  (*(volatile uint32_t *)(RCC_BASE + 0x18))

//GPIO
#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_CRL *(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_ODR *(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA_IDR *(volatile uint32_t *)(GPIOA_BASE + 0x08)


#define GPIOB_BASE 0x40010C00
#define GPIOB_CRH *(volatile uint32_t *)(GPIOB_BASE + 0x04)
#define GPIOB_CRL *(volatile uint32_t *)(GPIOB_BASE + 0x00)
#define GPIOB_ODR *(volatile uint32_t *)(GPIOB_BASE + 0x0C)
#define GPIOB_IDR *(volatile uint32_t *)(GPIOA_BASE + 0x08)


void clock_init()
{
	//Enable Init Clock GPIOA
	RCC_APB2ENR |= 1<<2;

	//Enable Init Clock GPIOB
	RCC_APB2ENR |= 1<<3;
}

void GPIO_init()
{
	GPIOA_CRL = 0x0;
	GPIOA_CRH = 0x0;

	GPIOB_CRL = 0x0;
	GPIOB_CRH = 0x0;

	//PA1 (Floating/High-Z) Input
	//00: Input mode (reset state)
	//01: Floating input (reset state)
	GPIOA_CRL |= (0b01<<6);

	//PB1 Push_Pull Output
	//00: General purpose output push-pull
	//01: Output mode, max speed 10 MHz.
	GPIOB_CRL |= (0b01<<4);

	//PA13 (Floating/High-Z) Input
	//00: Input mode (reset state)
	//01: Floating input (reset state)
	GPIOA_CRH |= (0b01<<22);

	//PB13 Push_Pull Output
	//00: General purpose output push-pull
	//01: Output mode, max speed 10 MHz.
	GPIOB_CRH |= (0b01<<20);

}

void delay(unsigned int x)
{
	unsigned int i,j;
	for(i=0;i<x;i++)
		for(j=0;j<255;j++);
}
int main(void)
{
	clock_init();
	GPIO_init();


	while(1)
	{
		// PA1 Bottom >> Pull_UP_R
		if( ((GPIOA_IDR & (1<<1) ) >> 1) == 0) //Press
		{
			GPIOB_ODR ^= (1<<1); //Toggle LED
			while( ((GPIOA_IDR & (1<<1) ) >> 1) == 0);//Single Press
		}
		// PA13 Bottom >> Pull_Down_R
		if( ((GPIOA_IDR & (1<<13) ) >> 13) == 1) // Multi Pressing
		{
			GPIOB_ODR ^= (1<<13);//Toggle LED
		}

		delay(1);
	}
}


