/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//#define MCU_Act_As_Master
#define MCU_Act_As_Slave


#include "stdint.h"
#include "STM32F103x6.h"
#include "STM32F103x6_GPIO.h"
#include "STM32F103x6_SPI.h"
#include "STM32F103x6_RCC.h"
#include "STM32F103x6_USART.h"


void clock_Init(void)
{
	//Enable Clock FOR GPIOA
	RCC_GPIOA_CLK_EN();
	//Enable Clock FOR GPIOB
	RCC_GPIOB_CLK_EN();

	//Enable AFIO Clock
	RCC_AFIO_CLK_EN();
}

uint16_t ch;

void SPI1_IRQ_CallBack(IRQ_SRC_t src_irq)
{
#ifdef	MCU_Act_As_Slave
	if(src_irq.RXNE)
	{
		ch =0xF;
		MCAL_SPI_TX_RX(SPI1, &ch, PollingDisable);
		MCAL_UART_SendData(USART1, &ch, enable);
	}
#endif
}
void UART_IRQ_CallBack(void)
{
#ifdef	MCU_Act_As_Master
	MCAL_UART_ReceiveData(USART1, &ch, disable);
	MCAL_UART_SendData(USART1, &ch, enable);
	//SPI Send
	MCAL_GPIO_WritePin(GPIOA,GPIO_PIN_4 ,0);
	MCAL_SPI_TX_RX(SPI1, &ch, PollingEnable);
	MCAL_GPIO_WritePin(GPIOA,GPIO_PIN_4 ,1);
#endif
}


int main(void)
{
	clock_Init();

	//==================UART INIT====================
	UART_Config UART_CFG;
	//PA9 -> TX
	//PA10 -> RX
	//PA11 -> CTS
	//PA12 -> RTS
	UART_CFG.BaudRate = UART_BAUD_RATE_115200;
	UART_CFG.HwFlowCtl= UART_HwFlowCtl_NONE;
	UART_CFG.Parity_Mode= UART_Parity_Mode_NONE;
	UART_CFG.IQR_Enable = UART_IRQ_Enable_RXNE;
	UART_CFG.Payload_Length =UART_PayLoad_Length_8B;
	UART_CFG.StopBits = UART_StopBits__1;
	UART_CFG.USART_Mode = UART_MODE_TX_RX;
	UART_CFG.P_IRQ_Handler = UART_IRQ_CallBack;

	MCAL_UART_Init(USART1, &UART_CFG);
	MCAL_UART_GPIO_Set_Pins(USART1);

	//==================SPI INIT====================
	//PA4 >> SPI1_NSS
	//PA5 >> SPI1_SCK
	//PA6 >> SPI1_MISO
	//PA7 >> SPI1_MOSI
	SPI_Config_t SPI_CFG;
	SPI_CFG.CLKPhase = SPI_Clock_Phase_2EDGE_first_data_capture_edge ;
	SPI_CFG.CLKPolarity = SPI_Clock_Polarity_HIGH_when_Idle ;
	SPI_CFG.Communication_Mode = SPI_DIRECTION_2LINES ;
	SPI_CFG.Frame_Format = SPI_Frame_Format_MSB_transmitted_first ;
	SPI_CFG.DataSize = SPI_Frame_Format_8B ;
	// Assume by default pclk2 = 8MHz
	SPI_CFG.SPI_BaudRatePrescaler = SPI_BaudRatePrescaler_8 ;// 1MHz

#ifdef	MCU_Act_As_Master
	SPI_CFG.Device_Mode = SPI_Device_Mode_MASTER ;
	SPI_CFG.IRQ_Enable = SPI_IRQ_Enable_NONE ;
	SPI_CFG.NSS = SPI_NSS_SW_NSSInternalSoft_Set ;
	SPI_CFG.P_IRQ_Handler = NULL ;

	// Configure SS in PA.4	by GPIO
	MCAL_GPIO_SET_Pin(GPIOA, GPIO_PIN_4,GPIO_MODE_Output_PP, GPIO_MAX_Speed_10M);
	//Force The Slave Select (HIGH) Idle Mode
	MCAL_GPIO_WritePin(GPIOA,GPIO_PIN_4 ,1);
#endif


#ifdef	MCU_Act_As_Slave
	SPI_CFG.Device_Mode = SPI_Device_Mode_SLAVE ;
	SPI_CFG.IRQ_Enable = SPI_IRQ_Enable_RXNEIE ;
	SPI_CFG.NSS = SPI_NSS_Hard_Slave ;
	SPI_CFG.P_IRQ_Handler = SPI1_IRQ_CallBack ;
#endif
	MCAL_SPI_Init(SPI1, &SPI_CFG);
	MCAL_SPI_GPIO_Set_Pins(SPI1);



	while(1)
	{
	}

}

















