/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32F103x6.h"
#include "STM32F103x6_GPIO.h"
#include "Keypad.h"
#include "LCD.h"

// 0 ---> 9 (for 7 Segment cathode)
#define ZERO 0x01
#define ONE 0x79
#define TWO 0x24
#define THREE 0x30
#define FOUR 0x4C
#define FIVE 0x12
#define SIX 0x02
#define SEVEN 0x19
#define EIGHT 0x00
#define NINE 0x10

void Clock_Init()
{
	//Enable Init Clock GPIOA
	RCC_GPIOA_CLK_EN() ;

	//Enable Init Clock GPIOB
	RCC_GPIOB_CLK_EN() ;
}

void GPIO_7SEG_Init()
{
	//PB9 Push_Pull Output / Output max speed 10 MHz.
	MCAL_GPIO_SET_Pin(GPIOB, GPIO_PIN_9,GPIO_MODE_Output_PP, GPIO_MAX_Speed_10M);

	//PB10 Push_Pull Output / Output max speed 10 MHz.
	MCAL_GPIO_SET_Pin(GPIOB, GPIO_PIN_10,GPIO_MODE_Output_PP, GPIO_MAX_Speed_10M);

	//PB11 Push_Pull Output / Output max speed 10 MHz.
	MCAL_GPIO_SET_Pin(GPIOB, GPIO_PIN_11,GPIO_MODE_Output_PP, GPIO_MAX_Speed_10M);

	//PB12 Push_Pull Output / Output max speed 10 MHz.
	MCAL_GPIO_SET_Pin(GPIOB, GPIO_PIN_12,GPIO_MODE_Output_PP, GPIO_MAX_Speed_10M);

	//PB13 Push_Pull Output / Output max speed 10 MHz.
	MCAL_GPIO_SET_Pin(GPIOB, GPIO_PIN_13,GPIO_MODE_Output_PP, GPIO_MAX_Speed_10M);

	//PB14 Push_Pull Output / Output max speed 10 MHz.
	MCAL_GPIO_SET_Pin(GPIOB, GPIO_PIN_14,GPIO_MODE_Output_PP, GPIO_MAX_Speed_10M);

	//PB15 Push_Pull Output / Output max speed 10 MHz.
	MCAL_GPIO_SET_Pin(GPIOB, GPIO_PIN_15,GPIO_MODE_Output_PP, GPIO_MAX_Speed_10M);
}


int main(void)
{
	int i;
	Clock_Init();
	LCD_init();
	LCD_Write_String("HEY");
	delay_ms(30);
	LCD_Clear_Screen();
	GPIO_7SEG_Init();
	unsigned char LCD_Display[]={'0','1','2','3','4','5','6','7','8','9','0'};// Display 0 ---> 9
	unsigned char Seven_Segment[]={ZERO,ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,EIGHT,NINE,ZERO};// 0 --->  9 --> 0 (for 7 Segment cathode)

	for (i = 0; i < 11; i++) {
		LCD_Write_Char(LCD_Display[i]);
		MCAL_GPIO_WritePort(GPIOB, (Seven_Segment[i])<<9); /* write data on to the LED port */
		delay_ms(100);
		/* wait for 1 second */
	}

	LCD_Clear_Screen();
	LCD_Write_String("Keypad is ready");
	LCD_Clear_Screen();
	KEYPAD_Init();
	delay_ms(30);
	char KeyPressed = 0;
	while(1)
	{
		KeyPressed = KEYPAD_Get_Char();
		switch(KeyPressed)
		{
		case '!' :
			LCD_Clear_Screen();
			break;
		case 'N' :// Do Nothing
			break;
		default :
			LCD_Write_Char(KeyPressed);
			break;
		}
		delay_ms(30);
	}
}




